### ISSUE TITLE
Fluid Shipping localization

### ISSUE THREAD

**Issue by DarkEviL88** [RavenDreamer/ONIMods#3]
It would be nice to be able to localize into another language.

**Comment by RavenDreamer** [comment]
@DarkEviL88 If you provide me with suitable translations, I'll see what I can do.

**Comment by DarkEviL88** [comment]
I'll probably do the translation today, but why not add the ability to translate the mod, as in other mods, through the .po file?

**Comment by DarkEviL88** [comment]
I tried to match the style of translation in the game. I don't know the in-game tags to make the words stand out with clickable links, so I enclosed the words in quotation marks.

Language: ru_RU

Bottle Filler - Наполнитель бутылок
Fills «Liquid» bottles from Internal storage. - Автоматически наполняет бутылки «жидкостью» из труб для ручной транспортировки.
Must be filled via Plumbing network. - Должен быть подключён к трубопроводу.
Bottle Fillers allow liquids piped to their internal storage to be hand-collected by Duplicants. - Бутылки позволяют дубликантам транспортировать жидкость с места на место.

Bottle Inserter - Опустошитель бутылок
Loads «Liquid» bottles into "Pipes" for transport. - Сливает «жидкость» из бутылок в "трубы".
Must be loaded by Duplicants. - Для доставки бутылок требуется дубликант.
Bottle Inserters allow contained liquids to be inserted directly into a pipe network. - Опустошители бутылок позволяют сливать жидкость из бутылок непосредственно в трубопровод.

Canister Inserter - Опустошитель канистр
Loads «Gas» canisters into "Pipes" for transport. - Сливает «газ» из канистр в "трубы".
Must be loaded by Duplicants. - Для доставки канистр требуется дубликант.
Canister Inserters allow contained gas to be inserted directly into a ventilation network. - Опустошители канистр позволяют сливать газ из канистр непосредственно трубопровод.

Options for Fluid Shipping - Опции для Доставки жидкости

Canister Inserter Volume - Объём опустошителя канистр
Internal storage volume of Canister Inserter (Kg). - Объём внутреннего хранилища опустошителя канистр (Кг).

Bottle Inserter Volume - Объём опустошителя бутылок
Internal storage volume of Bottle Inserter (Kg). - Объём внутреннего хранилища опустошителя бутылок (Кг).

Bottle Filler Volume - Объём наполнителя бутылок
Internal storage volume of Canister Inserter (Kg). - Объём внутреннего хранилища наполнителя бутылок (Кг).

Canister Inserter Power Requirement - Потребляемая мощность опустошителя канистр
Power requirement of Canister Inserter (W). - Потребляемая мощность опустошителя канистр (Вт).

Bottle Filler Power Requirement - Потребляемая мощность наполнителя бутылок
Power requirement of Bottle Filler (W). - Потребляемая мощность наполнителя бутылок (Вт).
